apiVersion: v1
kind: Namespace
metadata:
  name: devops-idcard
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: devops-idcard
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops-idcard
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Hello@123"
            - name: MYSQL_DATABASE
              value: "B-LA_VIREAK-db"
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: devops-idcard
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: final-web-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/B-LA_VIREAK-db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Hello@123"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 22
              name: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: devops-idcard
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30443
      name: http
    - port: 22
      targetPort: 22
      nodePort: 32222
      name: ssh
  selector:
    app: web-server
